// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_waldur

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func WaldurProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type WaldurModel struct {
}
