// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_openstack_image

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OpenstackImageDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"backend_id": schema.StringAttribute{
				Computed: true,
			},
			"min_disk": schema.Int64Attribute{
				Computed:            true,
				Description:         "Minimum disk size in MiB",
				MarkdownDescription: "Minimum disk size in MiB",
			},
			"min_ram": schema.Int64Attribute{
				Computed:            true,
				Description:         "Minimum memory size in MiB",
				MarkdownDescription: "Minimum memory size in MiB",
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"settings": schema.StringAttribute{
				Computed: true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
			"uuid": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type OpenstackImageModel struct {
	BackendId types.String `tfsdk:"backend_id"`
	MinDisk   types.Int64  `tfsdk:"min_disk"`
	MinRam    types.Int64  `tfsdk:"min_ram"`
	Name      types.String `tfsdk:"name"`
	Settings  types.String `tfsdk:"settings"`
	Url       types.String `tfsdk:"url"`
	Uuid      types.String `tfsdk:"uuid"`
}
