// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_openstack_network_rbac_policy

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OpenstackNetworkRbacPolicyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"backend_id": schema.StringAttribute{
				Computed: true,
			},
			"created": schema.StringAttribute{
				Computed: true,
			},
			"network": schema.StringAttribute{
				Computed: true,
			},
			"network_name": schema.StringAttribute{
				Computed: true,
			},
			"policy_type": schema.StringAttribute{
				Computed: true,
			},
			"target_tenant": schema.StringAttribute{
				Computed: true,
			},
			"target_tenant_name": schema.StringAttribute{
				Computed: true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
			"uuid": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type OpenstackNetworkRbacPolicyModel struct {
	BackendId        types.String `tfsdk:"backend_id"`
	Created          types.String `tfsdk:"created"`
	Network          types.String `tfsdk:"network"`
	NetworkName      types.String `tfsdk:"network_name"`
	PolicyType       types.String `tfsdk:"policy_type"`
	TargetTenant     types.String `tfsdk:"target_tenant"`
	TargetTenantName types.String `tfsdk:"target_tenant_name"`
	Url              types.String `tfsdk:"url"`
	Uuid             types.String `tfsdk:"uuid"`
}
