// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_openstack_routers

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func OpenstackRoutersResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"field": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtLeast(1),
				},
			},
			"project": schema.StringAttribute{
				Computed: true,
			},
			"service_settings": schema.StringAttribute{
				Computed: true,
			},
			"tenant": schema.StringAttribute{
				Required:            true,
				Description:         "OpenStack tenant this router belongs to",
				MarkdownDescription: "OpenStack tenant this router belongs to",
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
			"uuid": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type OpenstackRoutersModel struct {
	Field           types.List   `tfsdk:"field"`
	Name            types.String `tfsdk:"name"`
	Project         types.String `tfsdk:"project"`
	ServiceSettings types.String `tfsdk:"service_settings"`
	Tenant          types.String `tfsdk:"tenant"`
	Url             types.String `tfsdk:"url"`
	Uuid            types.String `tfsdk:"uuid"`
}
