// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_openstack_instance_availability_zone

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func OpenstackInstanceAvailabilityZoneDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"available": schema.BoolAttribute{
				Computed:            true,
				Description:         "Indicates whether this availability zone is available for instance provisioning",
				MarkdownDescription: "Indicates whether this availability zone is available for instance provisioning",
			},
			"name": schema.StringAttribute{
				Computed: true,
			},
			"settings": schema.StringAttribute{
				Computed: true,
			},
			"url": schema.StringAttribute{
				Computed: true,
			},
			"uuid": schema.StringAttribute{
				Required: true,
			},
		},
	}
}

type OpenstackInstanceAvailabilityZoneModel struct {
	Available types.Bool   `tfsdk:"available"`
	Name      types.String `tfsdk:"name"`
	Settings  types.String `tfsdk:"settings"`
	Url       types.String `tfsdk:"url"`
	Uuid      types.String `tfsdk:"uuid"`
}
